org.gradle.jvmargs  =-Xmx3G
org.gradle.daemon   =false

# Versions
minecraft_version       = 1.20.1
minecraft_version_range = [1.20.1]

forge_version           = 47.2.0
forge_version_range     = [47,)
loader_version_range    = [47,)

mapping_channel = official
mapping_version = 1.20.1

# Mod settings
mod_id          = swayaway
mod_name        = Sway Away
mod_license     = MIT License
mod_version     = 1.0
mod_group_id    = vonsnake
mod_authors     = Vonsnake
mod_description = Adds an additional View Bobbing option with view model only bobbing.

# Dependency settings
# This is forge, so Sodium is substituted with Embeddium
sodium_build_id         = 5681725


