# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs              = -Xmx2G
org.gradle.daemon               = true
org.gradle.parallel             = true
org.gradle.caching              = true
org.gradle.configuration-cache  = true

# Environment Properties
minecraft_version           = 1.21.1
minecraft_version_range     = [1.21.1,1.22)
neo_version                 = 21.1.215
neo_version_range           = [21,)
loader_version_range        = [4,)
parchment_minecraft_version = 1.21.1
parchment_mappings_version  = 2024.11.13

# Mod Properties
mod_id          = swayaway
mod_name        = Sway Away
mod_license     = MIT
mod_version     = 1.0
mod_group_id    = vonsnake
mod_authors     = Vonsnake
mod_description = Adds an additional View Bobbing option with view model only bobbing.

# Dependency settings
# Sodium is substituted with Embeddium
sodium_build_id         = 6118392